### ISSUE TITLE
是否可以支持转换 HTML Entity？

### ISSUE THREAD

**Issue by caocanx** [ZhgChgLi/ZMarkupParser#14]

**Comment by zhgchgli0718** [comment]
其實可以，但沒特別的做法；查到的方式都是直接把 HTML Entity 對應表放到程式中直接取代。
先放入 2023Q1 wishlist，沒人貢獻的話，我之後來做

**Comment by caocanx** [comment]
感谢！

**Comment by zhgchgli0718** [comment]
ref: https://github.com/Kitura/swift-html-entities
應該會直接引入

**Comment by caocanx** [comment]
赞！亲测好用
