### ISSUE TITLE
font tag 渲染顏色沒有效果，一些逃脫字元無法正常顯示

### ISSUE THREAD

**Issue by bevischen2** [ZhgChgLi/ZMarkupParser#22]
Hi 作者你好，

目前發現下面幾個問題：
1. `<font color="#008000">XXX</font> `顏色沒有效果
2. `&gt;` 沒有轉換
3. `&nbsp;` 沒有轉換

**Comment by bevischen2** [comment]
Hi 作者你好，

**Comment by bevischen2** [comment]
Hi zou

**Comment by bevischen2** [comment]
Hi 作者您好，

**Comment by bevischen2** [comment]
Hi 作者妳好，

目前發現下面幾個問題：
1. <font color="#008000">XXX</font> 顏色沒有效果
2. &gt; 沒有轉換
3. &nbsp; 沒有轉換

**Comment by zhgchgli0718** [comment]
查原因是 HTML Tag 太多了，沒有全部都實作；當初看 `<font>` Tag 已被[標示棄用](https://www.w3schools.com/tags/tag_font.asp)，就沒特別引入；但要實現也很容易，這週來擴充一下。

短期替代方式是改用 `<span>`

thanks!
