### ISSUE TITLE
图片不能显示

### ISSUE THREAD

**Issue by wudb** [ZhgChgLi/ZMarkupParser#43]
如下代码
let parser = ZHTMLParserBuilder.initWithDefault().set(rootStyle: MarkupStyle(font: MarkupStyleFont(size: 14))).build()
        let html = "<img src=\"https://cdn.sspai.com/editor/u_/clp6gmdb34tb3fodr3a0?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1\"/>"
        self.textView.setHtmlString(html, with: parser)

这个链接的图片不能显示

**Comment by zhgchgli0718** [comment]
v1.7.0 fixed and release
