### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by www-r3m1x** [ZhgChgLi/ZMarkupParser#44]
We use cocoapods and would like to use spacingPolicy. When is the new version planned to be released? Thanks!

**Comment by zhgchgli0718** [comment]
I am currently experiencing some issues with the Pod environment, which is preventing me from updating to the latest version of the Pod.
As a temporary solution, I recommend using SPM (Swift Package Manager).
I will work on resolving the Pod issues as soon as possible. Thank you for your understanding.

**Comment by zhgchgli0718** [comment]
The pod version 1.7.0 has been released. Thank you for your patience.
