### ISSUE TITLE
如何点击a标签的链接

### ISSUE THREAD

**Issue by qinlaoban** [ZhgChgLi/ZMarkupParser#46]
🔗

**Comment by zhgchgli0718** [comment]
https://www.hackingwithswift.com/example-code/system/how-to-make-tappable-links-in-nsattributedstring

**Comment by qinlaoban** [comment]
你好, 我没描述清楚. 我的意思是ZMarkupParser是否支持超链接点击.

**Comment by qinlaoban** [comment]
thanks
