### ISSUE TITLE
`stripper()` function doesn't remove HTML entities

### ISSUE THREAD

**Issue by cameroncooke** [ZhgChgLi/ZMarkupParser#51]
Given the following HTML string `<b>Tea &amp; coffee</b>`:

when rendered we get:
"**Tea &amp; coffee**"

when calling the `stripper()` method and rendered we get:
"Tea \&amp; coffee"

I would expect the HTML entities to be decoded, so when rendered:
"Tea & coffee" 

I can't see any use case where I would want an `NSAttributedString` that has been stripped of HTML formatting to show HTML entities which are by definition HTML.

**Comment by zhgchgli0718** [comment]
html stripper function is Powered by this repo https://github.com/alexisakers/HTMLString/tree/main
I would try to upgrade dependency to the lates version.
