### ISSUE TITLE
Does ZmarkupParser not need to apply a Privacy Manifest?

### ISSUE THREAD

**Issue by manunite** [ZhgChgLi/ZMarkupParser#53]
Apple policy requires libraries that use personal information to apply a Privacy Manifest, and I'm wondering if ZmarkupParser is unrelated to this.

**Comment by zhgchgli0718** [comment]
ZMarkupParser purely uses Swift and data structures to convert HTML strings into NSAttributedStrings. I believe it does not involve any privacy-related issues.

Thank you for your question.
