### ISSUE TITLE
Whitespace Issues

### ISSUE THREAD

**Issue by dabluck** [ZhgChgLi/ZMarkupParser#75]
Thanks for a useful library.

According to https://github.com/ZhgChgLi/ZMarkupParser/issues/47 the intention is to match browser output ignoring empty \<p> tags. But it doesn't handle it correctly if there is whitespace within tags. 

**Example HTML:**

```
<body>
    <p> ------ </p>
    <p>This is a paragraph.</p>
    <p> </p>
    <p></p>
    <p>     </p>
    <p></p>
    <p>This is a paragraph 2.</p>
    <p> ------ </p>
    <p>This is a paragraph.</p>
    <p>This is a paragraph 2.</p>
    <p> ------ </p>
</body>
```

**Browser result:**

<img width="209" alt="Screenshot 2024-08-28 at 10 00 19 AM" src="https://github.com/user-attachments/assets/2a6a8242-e04d-4579-9534-0fe92f42d699">

but in Zmarkup parser this looks like: 

<img width="176" alt="Screenshot 2024-08-28 at 9 58 40 AM" src="https://github.com/user-attachments/assets/0e685335-2412-466a-a605-d3066a468dc9">

**Comment by zhgchgli0718** [comment]
I'm quite busy right now, but I will fix it as soon as possible.
